CREATE TABLE IF NOT EXISTS `domain` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`path` VARCHAR(128) NOT NULL,
	`name` VARCHAR(128) NULL DEFAULT NULL,
	`comment` VARCHAR(512) NULL DEFAULT NULL,
	`created` TIMESTAMP NOT NULL,
	`lastmodified` TIMESTAMP NOT NULL,
	`status` ENUM('CREATED','MODIFIED','DELETED') NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `user` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`login` VARCHAR(32) NOT NULL,
	`password_sha` VARCHAR(128) NOT NULL,
	`password_reset_token` VARCHAR(128) NULL,
	`admin` BOOLEAN NOT NULL,
	`fullname` VARCHAR(128) NOT NULL,
	`affiliation` VARCHAR(128) NULL DEFAULT NULL,
	`email` VARCHAR(128) NULL DEFAULT NULL,
	`comment` VARCHAR(512) NULL DEFAULT NULL,
	`created` TIMESTAMP NOT NULL,
	`lastmodified` TIMESTAMP NOT NULL,
	`status` ENUM('CREATED','MODIFIED','DELETED') NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE INDEX `idx_login` (`login`)
);

CREATE TABLE IF NOT EXISTS `domainuser` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`user_id` INT NOT NULL,
	`domain_id` INT NOT NULL,
	`can_create` BOOLEAN NOT NULL,
	`can_modify` BOOLEAN NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `purl` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`path` VARCHAR(1024) NOT NULL,
	`domain_id` INT NOT NULL,
	`type` ENUM('FOUND_302','PARTIAL','GONE_410') NOT NULL,
	`target` VARCHAR(4096) NOT NULL,
	`created` TIMESTAMP NOT NULL,
	`lastmodified` TIMESTAMP NOT NULL,
	`status` ENUM('CREATED','MODIFIED','DELETED') NOT NULL,
	PRIMARY KEY (`id`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `purlhistory` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`purl_id` INT NOT NULL,
	`type` ENUM('FOUND_302','PARTIAL','GONE_410') NOT NULL,
	`target` VARCHAR(4096) NOT NULL,
	`modified` TIMESTAMP NOT NULL,
	`status` ENUM('CREATED','MODIFIED','DELETED') NOT NULL,
	PRIMARY KEY (`id`)
);
